# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encomenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
