# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encomenda', '0003_auto_20171106_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='quantidade',
            new_name='quatidade',
        ),
    ]
