# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_upload'),
        ('encomenda', '0005_auto_20171106_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
