# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_auto_20171110_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='telefone',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
