# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('funcionario', models.CharField(blank=True, default='', max_length=255)),
                ('total_vendas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('categoria', models.CharField(default='sem categoria', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
