# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
