# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cart_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='funcionario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
