# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20171109_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pagando',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cart',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
