# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('old_preco', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='category.Category')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
