# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(to='fornecedor.Fornecedor'),
        ),
    ]
