# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_fornecedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
