# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20170903_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='upload',
            field=models.FileField(blank=True, upload_to='produtos/'),
        ),
    ]
