# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20171106_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
