# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20171109_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Produtos'},
        ),
    ]
