# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='img',
            field=models.FileField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
