# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20171105_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
