# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20171107_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='compras_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
