# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20171107_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='compras_realizadas',
            field=models.IntegerField(default=1),
        ),
    ]
