# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_fornecedores'),
        ('vendas', '0002_auto_20170827_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='deu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
            preserve_default=False,
        ),
    ]
