# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20170827_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name_plural': 'Vendas'},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total_compra',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total_troco',
        ),
        migrations.AlterField(
            model_name='venda',
            name='total_valor',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_compra',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_troco',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_valor',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
