# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20170827_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total_compra',
        ),
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
