# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20170827_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='deu',
            field=models.DateTimeField(default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco',
            field=models.DateTimeField(default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total_troco',
            field=models.DateTimeField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_compra',
            field=models.DateTimeField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_troco',
            field=models.DateTimeField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ult_valor',
            field=models.DateTimeField(blank=True, default=0.0),
        ),
    ]
