# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_vender_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vender',
            name='email',
        ),
    ]
