# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0005_vender_total_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vender',
            name='troco',
        ),
    ]
