# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0007_remove_vender_total_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
